# Generated by Django 2.2.18 on 2022-08-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginlogout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='language_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
